import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,Check,ChevronRight,CircleUserRound,CreditCard,Delete,Minus,Plus,Printer,ReceiptText,ShoppingBag,Sparkles,Trash2,UtensilsCrossed,X}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
import'./styles.css';

const cats=[['combos','Todos os combos','🍔'],['burger','Hambúrgueres','🍔'],['fries','Batata frita','🍟'],['drinks','Bebidas','🥤'],['sweets','Sobremesas','🍦']];
const products=[
 {id:1,cat:'combos',name:'Combo Smash',desc:'Smash bacon, fritas crocantes e refrigerante',price:32.9,emoji:'🍔',tag:'Mais pedido',tone:'orange',custom:true},
 {id:2,cat:'combos',name:'Combo Duplo',desc:'Burger duplo, fritas médias e refrigerante',price:38.9,emoji:'🍔',tone:'red',custom:true},
 {id:3,cat:'combos',name:'Combo Chicken',desc:'Chicken crispy, fritas e refrigerante',price:34.5,emoji:'🍗',tag:'Novidade',tone:'yellow',custom:true},
 {id:4,cat:'burger',name:'Classic Burger',desc:'Carne 120g, queijo, salada e molho da casa',price:22.9,emoji:'🍔',tone:'green',custom:true},
 {id:5,cat:'burger',name:'Bacon Melt',desc:'Carne 150g, bacon, cheddar e cebola crispy',price:28.9,emoji:'🥓',tag:'Favorito',tone:'red',custom:true},
 {id:6,cat:'burger',name:'Veggie Fresh',desc:'Burger vegetal, queijo, rúcula e tomate',price:25.9,emoji:'🥬',tone:'green',custom:true},
 {id:7,cat:'fries',name:'Fritas da Casa',desc:'Sequinhas, crocantes e com sal na medida',price:11.9,emoji:'🍟',tone:'yellow',custom:true},
 {id:8,cat:'fries',name:'Fritas Cheddar',desc:'Fritas com cheddar cremoso e bacon',price:17.9,emoji:'🍟',tone:'orange',custom:true},
 {id:9,cat:'drinks',name:'Refrigerante',desc:'Escolha o seu sabor favorito',price:8.9,emoji:'🥤',tone:'red',custom:true},
 {id:10,cat:'drinks',name:'Limonada Fresh',desc:'Limão fresco, gelo e hortelã',price:10.9,emoji:'🍋',tone:'green'},
 {id:11,cat:'sweets',name:'Shake de Chocolate',desc:'Cremoso, gelado e irresistível',price:15.9,emoji:'🥤',tone:'brown'},
 {id:12,cat:'sweets',name:'Sundae Caramelo',desc:'Sorvete de baunilha com calda de caramelo',price:10.9,emoji:'🍦',tone:'blue'}
];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const API_BASE=import.meta.env.VITE_API_URL||'/api/v1';
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){let body=await response.json().catch(()=>({}));throw new Error(body.detail||'Não foi possível comunicar com o servidor.')}return response.json()}
function validCpf(v){let s=v.replace(/\D/g,'');if(s.length!==11||/^(\d)\1+$/.test(s))return false;for(let t=9;t<11;t++){let d=0;for(let i=0;i<t;i++)d+=+s[i]*((t+1)-i);d=((10*d)%11)%10;if(d!==+s[t])return false}return true}
function Brand(){return <div className="brand"><span><UtensilsCrossed/></span><b>SMASH<span>GO</span></b></div>}
function App(){
 const[page,setPage]=useState('welcome'),[name,setName]=useState(''),[cpf,setCpf]=useState(''),[active,setActive]=useState('combos'),[cart,setCart]=useState([]),[modal,setModal]=useState(null),[pay,setPay]=useState(null),[saving,setSaving]=useState(false),[savedOrder,setSavedOrder]=useState(null);
 const total=cart.reduce((s,i)=>s+i.price*i.qty,0),count=cart.reduce((s,i)=>s+i.qty,0);
 const add=(p,opts='')=>{setCart(c=>{let k=c.findIndex(x=>x.id===p.id&&x.opts===opts);if(k<0)return[...c,{...p,opts,qty:1}];return c.map((x,i)=>i===k?{...x,qty:x.qty+1}:x)});setModal(null)};
 const qty=(idx,d)=>setCart(c=>c.map((x,i)=>i===idx?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const reset=()=>{setPage('welcome');setName('');setCpf('');setCart([]);setPay(null);setSavedOrder(null)};
 const beginPayment=async method=>{if(saving)return;setSaving(true);try{let order=savedOrder;if(!order){order=await api('/orders',{method:'POST',body:JSON.stringify({customer:{name,cpf},items:cart.map(item=>({product_id:item.id,quantity:item.qty,size:item.size||null,meat_point:item.meat_point||null}))})});setSavedOrder(order)}await api(`/orders/${order.id}/payments`,{method:'POST',body:JSON.stringify({method})});setPay(method)}catch(error){alert(error.message)}finally{setSaving(false)}};
 if(page==='welcome')return <Welcome {...{name,setName,cpf,setCpf}} onGo={()=>setPage('menu')}/>;
 if(page==='cart')return <Cart {...{cart,total,qty,setCart}} back={()=>setPage('menu')} next={()=>setPage('payment')}/>;
 if(page==='payment')return <Payment {...{total,pay,saving,beginPayment}} back={()=>pay?setPay(null):setPage('cart')} done={()=>setPage('success')}/>;
 if(page==='success')return <Success {...{name,cart,total,reset}} orderNumber={savedOrder?.number}/>;
 let shown=active==='combos'?products.filter(p=>p.cat==='combos'):products.filter(p=>p.cat===active);
 return <div className="app-shell"><aside><Brand/><nav>{cats.map(([id,label,ico])=><button className={active===id?'active':''} onClick={()=>setActive(id)} key={id}><i>{ico}</i><span>{label}</span><ChevronRight/></button>)}</nav><div className="side-help"><Sparkles/><div><b>Feito na hora</b><small>do seu jeito</small></div></div></aside><main className="menu"><header><div><small>OLÁ, {name.split(' ')[0].toUpperCase()}!</small><h1>O que vai pedir hoje?</h1></div><button className="cart-btn" onClick={()=>setPage('cart')}><ShoppingBag/><span>{count}</span><div><small>SEU PEDIDO</small><b>{money(total)}</b></div></button></header><section className="category-title"><div><span>Cardápio</span><h2>{cats.find(c=>c[0]===active)[1]}</h2></div><small>{shown.length} opções</small></section><div className="grid">{shown.map(p=><Product p={p} key={p.id} add={()=>p.custom?setModal(p):add(p)}/>)}</div></main>{modal&&<Customize p={modal} close={()=>setModal(null)} add={add}/>}</div>
}
function Welcome({name,setName,cpf,setCpf,onGo}){const[focus,setFocus]=useState('name');let formatted=cpf.replace(/\D/g,'').slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');const key=k=>{if(k==='⌫'){focus==='name'?setName(v=>v.slice(0,-1)):setCpf(v=>v.slice(0,-1));return}if(k==='ESPAÇO'){if(focus==='name')setName(v=>v+' ');return}if(focus==='name')setName(v=>v+k);};return <div className="welcome"><div className="hero"><Brand/><div className="hero-copy"><span>SEU PEDIDO, DO SEU JEITO</span><h1>Bateu a fome?<br/><em>Bora resolver.</em></h1><p>Escolha, personalize e aproveite. É rápido, fácil e delicioso.</p></div><div className="hero-dots"><b>01</b><span></span><small>Peça</small><b>02</b><span></span><small>Pague</small><b>03</b><small>Aproveite</small></div></div><div className="identify"><div className="identify-head"><span><CircleUserRound/></span><div><small>VAMOS COMEÇAR</small><h2>Como podemos te chamar?</h2><p>Seus dados são usados apenas para identificar o pedido.</p></div></div><label className={focus==='name'?'focused':''}>SEU NOME<input value={name} onFocus={()=>setFocus('name')} readOnly placeholder="Toque aqui e digite seu nome"/></label><label className={focus==='cpf'?'focused':''}>CPF <small>(PARA NOTA FISCAL)</small><input value={formatted} onFocus={()=>setFocus('cpf')} readOnly placeholder="000.000.000-00"/><i className={validCpf(cpf)?'ok':''}>{cpf.length?validCpf(cpf)?<Check/>:<X/>:null}</i></label>{focus==='cpf'?<Numpad press={k=>k==='⌫'?setCpf(v=>v.slice(0,-1)):setCpf(v=>(v+k).slice(0,11))}/>:<Keyboard press={key}/>}<button className="continue" disabled={name.trim().length<2||!validCpf(cpf)} onClick={onGo}>Ver cardápio <ChevronRight/></button></div></div>}
const Keyboard=({press})=><div className="keyboard">{'QWERTYUIOPASDFGHJKLÇZXCVBNM'.split('').map(k=><button onClick={()=>press(k)} key={k}>{k}</button>)}<button className="space" onClick={()=>press('ESPAÇO')}>ESPAÇO</button><button className="del" onClick={()=>press('⌫')}><Delete/></button></div>;
const Numpad=({press})=><div className="numpad">{'123456789'.split('').map(k=><button onClick={()=>press(k)} key={k}>{k}</button>)}<button className="clear" onClick={()=>press('⌫')}><Delete/></button><button onClick={()=>press('0')}>0</button><button className="clear" onClick={()=>press('⌫')}>APAGAR</button></div>;
function Product({p,add}){return <article className="product"><div className={'food '+p.tone}><span>{p.emoji}</span>{p.tag&&<b>{p.tag}</b>}</div><div className="product-info"><h3>{p.name}</h3><p>{p.desc}</p><footer><strong>{money(p.price)}</strong><button onClick={add}><Plus/> Adicionar</button></footer></div></article>}
function Customize({p,close,add}){const[size,setSize]=useState('Médio'),[point,setPoint]=useState('Ao ponto');let extra=size==='Grande'?4:size==='Pequeno'?-2:0;return <div className="overlay"><div className="modal"><button className="x" onClick={close}><X/></button><div className={'modal-food '+p.tone}><span>{p.emoji}</span></div><div className="modal-body"><small>PERSONALIZE</small><h2>{p.name}</h2><p>{p.desc}</p><Option title="Escolha o tamanho" items={['Pequeno','Médio','Grande']} value={size} set={setSize}/>{(p.cat==='burger'||p.cat==='combos')&&<Option title="Ponto da carne" items={['Ao ponto','Bem passada']} value={point} set={setPoint}/>}<button className="add-modal" onClick={()=>add({...p,price:p.price+extra,size,meat_point:(p.cat==='burger'||p.cat==='combos')?point:null},`${size} · ${point}`)}><span>Adicionar ao pedido</span><b>{money(p.price+extra)}</b></button></div></div></div>}
function Option({title,items,value,set}){return <div className="option"><h4>{title}</h4><div>{items.map(i=><button className={value===i?'selected':''} onClick={()=>set(i)} key={i}>{i}{value===i&&<Check/>}</button>)}</div></div>}
function Top({title,back}){return <header className="top"><button onClick={back}><ArrowLeft/></button><Brand/><span>{title}</span></header>}
function Cart({cart,total,qty,setCart,back,next}){return <div className="light-page"><Top title="Seu pedido" back={back}/><div className="cart-layout"><section><div className="step"><b>1</b><div><h1>Revise seu pedido</h1><p>Confira os itens antes de seguir para o pagamento.</p></div></div>{cart.length?cart.map((x,i)=><div className="cart-item" key={i}><div className={'thumb '+x.tone}>{x.emoji}</div><div className="item-text"><h3>{x.name}</h3><p>{x.opts||x.desc}</p><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Trash2/> Remover</button></div><div className="counter"><button onClick={()=>qty(i,-1)}><Minus/></button><b>{x.qty}</b><button onClick={()=>qty(i,1)}><Plus/></button></div><strong>{money(x.price*x.qty)}</strong></div>):<div className="empty"><ShoppingBag/><h2>Seu pedido está vazio</h2><button onClick={back}>Voltar ao cardápio</button></div>}</section><aside className="summary"><ReceiptText/><h2>Resumo</h2><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Taxas</span><b>R$ 0,00</b></div><hr/><div className="total"><span>Total</span><b>{money(total)}</b></div><button disabled={!cart.length} onClick={next}>Fazer pagamento <ChevronRight/></button><button className="link" onClick={back}>Continuar comprando</button></aside></div></div>}
function Payment({total,pay,back,done,saving,beginPayment}){const[status,setStatus]=useState('waiting');useEffect(()=>{if(!pay)return;setStatus('waiting');let a=setTimeout(()=>setStatus('processing'),2500),b=setTimeout(()=>setStatus('approved'),5000),c=setTimeout(done,6500);return()=>[a,b,c].forEach(clearTimeout)},[pay]);if(pay)return <div className="light-page"><Top title="Pagamento" back={back}/><div className="pay-process">{pay==='pix'?<><div className="qr"><QRCodeSVG value="00020126580014BR.GOV.BCB.PIX0136smashgo-pedido-2026-0042" size={230}/></div><small>ESCANEIE COM O APP DO SEU BANCO</small><h1>Pagamento via Pix</h1><p>Este código expira em <b>04:58</b></p></>:<><div className={'card-machine '+status}><CreditCard/><i></i></div><small>{status==='waiting'?'AGUARDANDO CARTÃO':status==='processing'?'PROCESSANDO...':'PAGAMENTO APROVADO'}</small><h1>{status==='approved'?'Tudo certo!':'Insira ou aproxime seu cartão'}</h1><p>Não retire o cartão até a confirmação.</p></>}<div className={'status '+status}>{status==='approved'?<Check/>:<span></span>}{status==='waiting'?'Aguardando pagamento':status==='processing'?'Confirmando pagamento':'Pagamento aprovado'}</div></div></div>;return <div className="light-page"><Top title="Pagamento" back={back}/><div className="payment"><div className="step"><b>2</b><div><h1>Como você quer pagar?</h1><p>Escolha uma forma de pagamento para continuar.</p></div></div><div className="pay-grid"><button disabled={saving} onClick={()=>beginPayment('credit')}><span><CreditCard/></span><h2>Crédito</h2><p>{saving?'Salvando pedido...':'Insira ou aproxime'}</p><ChevronRight/></button><button disabled={saving} onClick={()=>beginPayment('debit')}><span><CreditCard/></span><h2>Débito</h2><p>{saving?'Salvando pedido...':'Insira ou aproxime'}</p><ChevronRight/></button><button disabled={saving} onClick={()=>beginPayment('pix')}><span className="pix">◆</span><h2>Pix</h2><p>{saving?'Salvando pedido...':'Escaneie o QR Code'}</p><ChevronRight/></button></div><div className="amount"><span>Total a pagar</span><b>{money(total)}</b></div></div></div>}
function Success({name,cart,total,reset,orderNumber}){const[sec,setSec]=useState(15);useEffect(()=>{let t=setInterval(()=>setSec(s=>{if(s<=1){clearInterval(t);reset();return 0}return s-1}),1000);return()=>clearInterval(t)},[]);return <div className="success"><Brand/><div className="success-card"><div className="success-icon"><Check/></div><small>PAGAMENTO APROVADO</small><h1>Pedido confirmado!</h1><p>Obrigado, {name.split(' ')[0]}! Já estamos preparando tudo.</p><div className="order"><small>SUA SENHA É</small><strong>{orderNumber||'---'}</strong><span>Acompanhe a chamada no painel</span></div><div className="receipt"><div><ReceiptText/><span>{cart.reduce((s,x)=>s+x.qty,0)} itens</span></div><b>{money(total)}</b></div><div className="printing"><Printer/> Imprimindo seu comprovante...</div><button onClick={reset}>Finalizar agora</button><p className="countdown">Nova compra em <b>{sec}s</b></p></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
